import React, { useMemo, useState } from 'react'

const fmtUsd = (v) => {
  const n = Number(v)
  if (!isFinite(n)) return '—'
  if (Math.abs(n) >= 1e9) return '$' + (n / 1e9).toFixed(2) + 'B'
  if (Math.abs(n) >= 1e6) return '$' + (n / 1e6).toFixed(2) + 'M'
  if (Math.abs(n) >= 1e3) return '$' + (n / 1e3).toFixed(0) + 'k'
  return '$' + n.toFixed(0)
}
const fmtFee = (f) => (f == null ? null : (f * 100).toFixed(f < 0.001 ? 3 : 2).replace(/\.?0+$/, '') + '%')

// Fee-derived figures are estimates: GeckoTerminal has no fee field, so the
// tier comes from the pool name and the result is gross fees generated, not
// LP take-home. Anything downstream of that is marked in the UI.
const feeApr = (p) => (p.fees24 == null || !(p.tvl > 0) ? null : (p.fees24 * 365 * 100) / p.tvl)

// How Uniswap's own app would treat the pool, derived from its token lists.
const LISTING = {
  listed:        { label: 'listed',      cls: 'lst-ok',    t: 'Both tokens are on Uniswap\u2019s default list — this pool shows up normally in the app.' },
  'search-only': { label: 'search only', cls: 'lst-warn',  t: 'Tokens are on the extended list: findable in the app, but only if you search for them.' },
  unlisted:      { label: 'UNLISTED',    cls: 'lst-hide',  t: 'At least one token is on none of Uniswap\u2019s lists. You cannot reach this pool by browsing the app — only by pasting the address, behind warnings.' },
  blocked:       { label: 'BLOCKED',     cls: 'lst-block', t: 'A token is on Uniswap\u2019s UNSUPPORTED list. The interface actively blocks or warns against this pool.' },
  unknown:       { label: '—',           cls: 'dim',       t: 'Token addresses or chain id unavailable, so listing status could not be determined.' },
}

const COLS = [
  { k: 'name', l: 'Pool', a: 'l' },
  { k: 'listing', l: 'In the app?', a: 'l', t: 'Whether Uniswap\u2019s own interface will show you this pool, judged against its default / extended / unsupported token lists.' },
  { k: 'version', l: 'Ver', a: 'l' },
  { k: 'chain', l: 'Chain', a: 'l' },
  { k: 'swapFee', l: 'Fee tier', a: 'r', t: 'Read from the pool name — GeckoTerminal exposes no fee field. v2 is a fixed 0.30%. Blank for v4 dynamic-fee and hook pools.' },
  { k: 'tvl', l: 'TVL', a: 'r', t: 'Reserves in USD, straight from GeckoTerminal. Verified against the live API to within 0.02%.' },
  { k: 'vol24', l: 'Volume 24h', a: 'r', t: 'Straight from GeckoTerminal.' },
  { k: 'fees24', l: 'Fees 24h', a: 'r', t: 'ESTIMATE: 24h volume × the fee tier. Gross fees generated by swaps, not LP take-home — v3 can have a protocol fee enabled and v4 hooks may take a cut, neither of which this source reports.' },
  { k: 'apr', l: 'Fee APR', a: 'r', t: 'ESTIMATE: annualised 24h fees over TVL. Inherits every caveat of the fees column, and one day of volume is a thin basis for an annual rate.' },
  { k: 'turnover', l: 'Vol/TVL', a: 'r', t: 'How many times the pool’s own liquidity traded in 24h. High values often mean a very thin pool rather than a busy one.' },
  { k: 'txns24', l: 'Txns 24h', a: 'r' },
]

function sortVal(p, k) {
  switch (k) {
    case 'name': return (p.name || '').toLowerCase()
    case 'listing': return ['unlisted', 'blocked', 'search-only', 'listed', 'unknown'].indexOf(p.listing)
    case 'version': return p.version
    case 'chain': return p.chain.toLowerCase()
    case 'swapFee': return p.swapFee
    case 'tvl': return p.tvl
    case 'vol24': return p.vol24
    case 'fees24': return p.fees24
    case 'apr': return feeApr(p)
    case 'turnover': return p.tvl > 0 ? p.vol24 / p.tvl : null
    case 'txns24': return p.txns24
    default: return null
  }
}

function toCsv(rows) {
  const head = ['pool', 'version', 'chain', 'address', 'fee_tier', 'fee_source', 'tvl_usd',
    'volume_24h_usd', 'fees_24h_usd_estimated', 'fee_apr_pct_estimated', 'vol_over_tvl', 'txns_24h', 'created', 'app_listing', 'flags']
  const esc = (v) => { const s = v == null ? '' : String(v); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s }
  return [head.join(','), ...rows.map((p) => [
    p.name, 'v' + p.version, p.chain, p.address, p.swapFee ?? '', p.feeSource, p.tvl,
    p.vol24, p.fees24 ?? '', feeApr(p)?.toFixed(2) ?? '', p.tvl > 0 ? (p.vol24 / p.tvl).toFixed(3) : '',
    p.txns24, p.created, p.listing, (p.flags || []).join(' '),
  ].map(esc).join(','))].join('\n')
}

export default function PoolTable({ data }) {
  const all = data.pools
  const [sort, setSort] = useState({ k: 'tvl', d: 'desc' })
  const [q, setQ] = useState('')
  const [chain, setChain] = useState('ALL')
  const [ver, setVer] = useState('ALL')
  const [minTvl, setMinTvl] = useState(1000)
  const [hideSuspect, setHideSuspect] = useState(true)
  const [onlyHidden, setOnlyHidden] = useState(false)

  const chains = useMemo(() => {
    const m = new Map()
    for (const p of all) m.set(p.chain, (m.get(p.chain) || 0) + 1)
    return [...m.entries()].sort((a, b) => b[1] - a[1])
  }, [all])

  const rows = useMemo(() => {
    const needle = q.trim().toLowerCase()
    const out = all.filter(
      (p) =>
        (chain === 'ALL' || p.chain === chain) &&
        (ver === 'ALL' || p.version === +ver) &&
        p.tvl >= minTvl &&
        (!hideSuspect || !(p.flags || []).includes('vol-tvl-outlier')) &&
        (!onlyHidden || p.listing === 'unlisted' || p.listing === 'blocked') &&
        (!needle || (p.name || '').toLowerCase().includes(needle) ||
          p.address?.toLowerCase().includes(needle) || p.chain.toLowerCase().includes(needle))
    )
    out.sort((a, b) => {
      const va = sortVal(a, sort.k)
      const vb = sortVal(b, sort.k)
      if (va == null && vb == null) return 0
      if (va == null) return 1
      if (vb == null) return -1
      if (typeof va === 'string') return sort.d === 'asc' ? va.localeCompare(vb) : vb.localeCompare(va)
      return sort.d === 'asc' ? va - vb : vb - va
    })
    return out
  }, [all, q, chain, ver, minTvl, hideSuspect, onlyHidden, sort])

  const click = (k) =>
    setSort((s) => (s.k === k ? { k, d: s.d === 'asc' ? 'desc' : 'asc' }
      : { k, d: ['name', 'chain'].includes(k) ? 'asc' : 'desc' }))

  const tvlSum = rows.reduce((a, p) => a + p.tvl, 0)
  const volSum = rows.reduce((a, p) => a + p.vol24, 0)
  const feeSum = rows.reduce((a, p) => a + (p.fees24 || 0), 0)
  const unknownFee = rows.filter((p) => p.swapFee == null).length
  const hiddenRows = rows.filter((p) => p.listing === 'unlisted' || p.listing === 'blocked')
  const hiddenTvl = hiddenRows.reduce((a, p) => a + p.tvl, 0)

  function downloadCsv() {
    const blob = new Blob([toCsv(rows)], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `uniswap-pools-${String(data.generatedAt).slice(0, 10)}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <>
      <div className="statstrip">
        <div><span className="sl">Pools</span><span className="sv">{rows.length.toLocaleString()}</span></div>
        <div><span className="sl">Total TVL</span><span className="sv">{fmtUsd(tvlSum)}</span></div>
        <div><span className="sl">Volume 24h</span><span className="sv">{fmtUsd(volSum)}</span></div>
        <div>
          <span className="sl">Fees 24h (est.)</span>
          <span className="sv">{fmtUsd(feeSum)}<span className="sv-sub"> · {unknownFee} unknown</span></span>
        </div>
        <div>
          <span className="sl">Not in the Uniswap app</span>
          <span className="sv" style={{ color: 'var(--amber)' }}>
            {hiddenRows.length.toLocaleString()}
            <span className="sv-sub"> · {fmtUsd(hiddenTvl)} TVL</span>
          </span>
        </div>
        <div><span className="sl">Updated</span><span className="sv sm">{String(data.generatedAt).slice(0, 10)}</span></div>
      </div>

      <div className="fbar">
        <span className="prompt">&gt;</span>
        <input className="fsearch" type="text" placeholder="search pair, chain or address…"
               value={q} onChange={(e) => setQ(e.target.value)} spellCheck={false} />
        <span className="fgroup">
          <span className="flabel">CHAIN</span>
          <select value={chain} onChange={(e) => setChain(e.target.value)}>
            <option value="ALL">ALL</option>
            {chains.map(([c, n]) => <option key={c} value={c}>{c} ({n})</option>)}
          </select>
        </span>
        <span className="fgroup">
          <span className="flabel">VERSION</span>
          <select value={ver} onChange={(e) => setVer(e.target.value)}>
            <option value="ALL">ALL</option>
            <option value="2">v2</option>
            <option value="3">v3</option>
            <option value="4">v4</option>
          </select>
        </span>
        <span className="fgroup">
          <span className="flabel">MIN-TVL</span>
          <select value={minTvl} onChange={(e) => setMinTvl(+e.target.value)}>
            <option value={0}>ANY</option>
            <option value={1000}>$1K</option>
            <option value={10000}>$10K</option>
            <option value={100000}>$100K</option>
            <option value={1000000}>$1M</option>
          </select>
        </span>
        <button className={'fbtn' + (onlyHidden ? ' on' : '')} onClick={() => setOnlyHidden((v) => !v)}
                title="Only pools you cannot reach by browsing the Uniswap app — a token on none of its lists, or on the unsupported list">
          [ NOT IN THE APP ]
        </button>
        <span className="muted tinystat" style={{ marginLeft: 'auto' }}>
          {rows.filter((p) => p.flags?.includes('extreme-fee')).length} charge over 1%
        </span>
        <button className={'fbtn' + (hideSuspect ? ' on' : '')} onClick={() => setHideSuspect((v) => !v)}
                title="Hide pools trading more than 50x their own TVL in 24h — usually a near-empty pool rather than a busy one, which makes the APR estimate meaningless">
          [ {hideSuspect ? 'HIDING' : 'SHOWING'} OUTLIERS ]
        </button>
        <button className="fbtn" onClick={downloadCsv} disabled={!rows.length}>[ CSV ]</button>
      </div>

      <div className="tablewrap">
        <table className="pooltable">
          <thead>
            <tr>
              {COLS.map((c) => (
                <th key={c.k} className={`${c.a === 'r' ? 'r' : ''} ${sort.k === c.k ? 'sorted' : ''}`}
                    onClick={() => click(c.k)} title={c.t}>
                  {c.l}<span className="arrow">{sort.k === c.k ? (sort.d === 'asc' ? '▲' : '▼') : '·'}</span>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.slice(0, 600).map((p) => {
              const apr = feeApr(p)
              const turnover = p.tvl > 0 ? p.vol24 / p.tvl : null
              const ex = data.chains.find((c) => c.name === p.chain)?.explorer
              return (
                <tr key={p.id}>
                  <td className="pool">
                    {ex
                      ? <a className="pairname" href={ex + p.address} target="_blank" rel="noreferrer">{p.name || p.address}</a>
                      : <span className="pairname">{p.name || p.address}</span>}
                  </td>
                  <td>
                    <span className={'lstag ' + (LISTING[p.listing]?.cls || 'dim')}
                          title={LISTING[p.listing]?.t}>
                      {LISTING[p.listing]?.label || p.listing}
                    </span>
                  </td>
                  <td><span className={'vtag v' + p.version}>v{p.version}</span></td>
                  <td><span className="chaintag">{p.short}</span></td>
                  <td className="r num feepill">
                    {p.swapFee != null
                      ? <span className={p.flags?.includes('extreme-fee') ? 'extreme' : undefined}
                              title={p.flags?.includes('extreme-fee')
                                ? `A ${(p.swapFee * 100).toFixed(1)}% fee takes most of every trade. Real, not a parsing error — v4 permits any fee, and v3 pools here land exactly on the four canonical tiers.`
                                : undefined}>
                          {fmtFee(p.swapFee)}
                        </span>
                      : <span className="dim" title={p.feeSource === 'dynamic-or-hook'
                          ? 'v4 dynamic-fee or hook pool — no static tier in the pool name, so no fee is claimed'
                          : 'No fee tier available from this source'}>dynamic</span>}
                  </td>
                  <td className="r num">{fmtUsd(p.tvl)}</td>
                  <td className="r num">{fmtUsd(p.vol24)}</td>
                  <td className="r num est-val">
                    {p.fees24 != null ? fmtUsd(p.fees24) : <span className="dim">—</span>}
                  </td>
                  <td className="r num est-val">
                    {apr != null ? apr.toFixed(apr >= 100 ? 0 : 1) + '%' : <span className="dim">—</span>}
                  </td>
                  <td className="r num dimtext">
                    {turnover != null ? turnover.toFixed(turnover >= 10 ? 0 : 2) + '×' : <span className="dim">—</span>}
                  </td>
                  <td className="r num dimtext">{p.txns24 ? p.txns24.toLocaleString() : <span className="dim">—</span>}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
        {rows.length > 600 && (
          <div className="loading">Showing the top 600 of {rows.length.toLocaleString()} — narrow the filters or export CSV for the rest.</div>
        )}
        {!rows.length && <div className="loading">No pools match those filters.</div>}
      </div>

      <p className="foot">
        <b>What is measured, and what is estimated.</b> <b>TVL</b>, <b>volume</b> and <b>transactions</b>
        come straight from GeckoTerminal and were checked against the live API — WETH/USDC 0.05% on
        Ethereum reads $99,279,920 here against $99,262,200 there. <b>Fees</b> and <b>fee APR</b> are
        <span className="est">EST</span> estimates: GeckoTerminal exposes no fee field, so the tier is
        read from the pool name and multiplied by volume. That is <b>gross fees generated</b>, not LP
        take-home — v3 pools can have a protocol fee enabled and v4 hooks may take a cut, and neither
        is visible here. Pools whose fee cannot be established, including v4 dynamic-fee and hook
        pools, show <span className="dim">dynamic</span> rather than a fabricated number. Fees above
        1% are marked <span className="extreme">in red</span>: impossible on v3, whose top tier is
        1%, but permitted on v4, where some pools charge 90% or more. Those are genuine — every v3
        pool here lands on exactly one of the four canonical tiers, which is what confirms the tier
        is being read correctly.
        {' '}<b>Not in the app.</b> Uniswap's interface only browses pools whose tokens are on its
        own lists. Each pool is checked against the <b>default</b>, <b>extended</b> and
        <b>unsupported</b> lists Uniswap publishes: <span className="lstag lst-hide">UNLISTED</span>
        means a token is on none of them, so the pool is reachable only by pasting an address behind
        warnings, and <span className="lstag lst-block">BLOCKED</span> means a token is on the
        unsupported list outright. Both are real pools with real liquidity — being absent from the
        app is a curation decision, not a verdict on the pool, and plenty of them are best avoided.
        {' '}<b>Coverage.</b> {data.coverageNote}
        {' '}Sourced per Uniswap version per chain, so it is not skewed toward pools that happen to
        rank highly across all DEXes at once. Data refreshed {String(data.generatedAt).slice(0, 10)}.
      </p>
    </>
  )
}
